version: '3.3'

services:
  app:
    image: ${IMAGE:-eic-contracts:latest}
    links:
      - mongo
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_URI=mongodb://mongo:27017/contracts
      - MONGO_COLLECTION=contracts
      - EIC_CUSTOMERS_SERVICE_PROTOCOL=http
      - EIC_CUSTOMERS_SERVICE_HOST=localhost
      - EIC_CUSTOMERS_SERVICE_PORT=8088
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
